apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o5x89yu1e-nodejs
  janus-idp.io/tekton: o5x89yu1e-nodejs
  backstage.io/kubernetes-id: o5x89yu1e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o5x89yu1e-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
