apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: o5x89yu1e-nodejs-gitops
  description: This is GitOps manifest for o5x89yu1e-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=o5x89yu1e-nodejs
    backstage.io/kubernetes-id: o5x89yu1e-nodejs 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: tnevrlka-rhtap/o5x89yu1e-nodejs-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:o5x89yu1e-nodejs
